defaults: &defaults
  working_directory: ~/ff1randomizer
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: publish
          command: |
            cd FF1RandomizerOnline
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet publish -c Release
              git rev-parse HEAD > bin/Release/netcoreapp2.0/publish/version.txt
            else
              dotnet publish -c Debug
              git rev-parse HEAD > bin/Debug/netcoreapp2.0/publish/version.txt
            fi
      - persist_to_workspace:
          root: ~/ff1randomizer
          paths: FF1RandomizerOnline

  dockerize_production:
    <<: *defaults
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/ff1randomizer
      - run:
          name: docker
          command: |
            cd FF1RandomizerOnline && \
            docker login -u $DOCKER_USER -p $DOCKER_PASS && \
            docker build -t entroper/finalfantasyrandomizer:latest -f Dockerfile . && \
            docker push entroper/finalfantasyrandomizer:latest

  dockerize_beta:
    <<: *defaults
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/ff1randomizer
      - run:
          name: docker
          command: |
            cd FF1RandomizerOnline && \
            docker login -u $DOCKER_USER -p $DOCKER_PASS && \
            docker build -t entroper/finalfantasyrandomizer:beta -f Dockerfile.debug . && \
            docker push entroper/finalfantasyrandomizer:beta

  dockerize_alpha:
    <<: *defaults
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/ff1randomizer
      - run:
          name: docker
          command: |
            cd FF1RandomizerOnline && \
            docker login -u $DOCKER_USER -p $DOCKER_PASS && \
            docker build -t entroper/finalfantasyrandomizer:alpha -f Dockerfile.debug . && \
            docker push entroper/finalfantasyrandomizer:alpha

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            mkdir -p ~/.ssh && \
            cp .ssh/known_hosts ~/.ssh/known_hosts && \
            ssh circle@finalfantasyrandomizer.com "./deployff1r.sh master"

  deploy_beta:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            mkdir -p ~/.ssh && \
            cp .ssh/known_hosts ~/.ssh/known_hosts && \
            ssh circle@finalfantasyrandomizer.com "./deployff1r.sh beta"

  deploy_alpha:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            mkdir -p ~/.ssh && \
            cp .ssh/known_hosts ~/.ssh/known_hosts && \
            ssh circle@finalfantasyrandomizer.com "./deployff1r.sh alpha"

workflows:
  version: 2
  main:
    jobs:
      - build
      - dockerize_production:
          requires:
            - build
          filters:
            branches:
              only: master
      - dockerize_beta:
          requires:
            - build
          filters:
            branches:
              only: dev
      - dockerize_alpha:
          requires:
            - build
          filters:
            branches:
              only: alpha
      - deploy_production:
          requires:
            - dockerize_production
          filters:
            branches:
              only: master
      - deploy_beta:
          requires:
            - dockerize_beta
          filters:
            branches:
              only: dev
      - deploy_alpha:
          requires:
            - dockerize_alpha
          filters:
            branches:
              only: alpha
